### ISSUE TITLE
Improvements for Quality section

### ISSUE THREAD

**Issue by Michaelangel007** [willhuynh/VendorRecipeCheatsheet#3]
1. May want to remove the vertical bar between the `20% | 40% Total` since it looks out of place.
2. May want to consider changing the middle bar of the 2x3 table to be dotted
3. Does the `Quality` header need a lighter background like `Crafting` / `Utility` ?

Example:
```
      20%       40%
    +-------+--------+
    | Flask : Flasks |
    +-------:--------+
    | Gem   : Gems   |
    +-------:--------+
    | Map   : Maps   |
    +-------:--------+

```

**Comment by willhuynh** [comment]
Will update with this info in next version: v1.1.1
